## Numpy array and basics
Learn about numpy with chai aur code

In [1]:
import numpy as np

### creating array from list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

1D Array: [1 2 3 4 5]


In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:", arr_2d)

2D Array: [[1 2 3]
 [4 5 6]]


numpy optimised hi isliy hai kyoki vo similar data-types par work karta hai

### List vs numpy array

In [4]:
py_list = [1, 2, 3]
print("Python list Multiplication", py_list*2)

Python list Multiplication [1, 2, 3, 1, 2, 3]


In [5]:
np_array = np.array([1, 2, 3]) #here element wise multiplication happen
print("Pyhton Array Multiplication", np_array*2)

Pyhton Array Multiplication [2 4 6]


In [6]:
py_list = [1, 2, 3]
print("Python list Multiplication", py_list*2)


np_array = np.array([1, 2, 3]) #here element wise multiplication happen
print("Pyhton Array Multiplication", np_array*2)



import time 
start = time.time()
py_list = [i*2 for i in range (1000000)]
print("\n List operation time:", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time:", time.time() - start)

Python list Multiplication [1, 2, 3, 1, 2, 3]
Pyhton Array Multiplication [2 4 6]

 List operation time: 0.07642960548400879

 Numpy operation time: 0.007967472076416016


### Creating Array from Scratch

In [7]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones((2,3))
print("ones array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2,3))
print("random array: \n", random)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.43110738 0.52969858 0.62831691]
 [0.33705201 0.84481843 0.47741996]]


In [8]:
sequence = np.arange(0, 10, 2)
print("sequence array: \n", sequence)

sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [9]:
vector = np.array([1, 2, 3])
print("Vector: \n", vector)



matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("Matrix: \n", matrix)


tensor =np.array([[[1, 2],[3, 4]],
                 [[5, 6], [7,8]]])
print("Tensor: \n", tensor)



Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [10]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])
print("Shape: \n", arr.shape)
print("Dimention: \n", arr.ndim)
print("Size: \n", arr.size)
print("DType \n", arr.dtype)


Shape: 
 (2, 3)
Dimention: 
 2
Size: 
 6
DType 
 int64


### Array Reshaping

In [11]:
arr = np.arange(12)
print("Original Array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped Array ", reshaped)

flattend = reshaped.flatten()
print("\n Flattened Array ", flattend)


# ravel (returns vies, instead of copy)


raveled = reshaped.ravel()
print("Reveled Array ", raveled)


#transpose
transpose = reshaped.T
print("Transposed Array ", transpose)

Original Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reveled Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
